### ISSUE TITLE
Raise error when local context is defined on operation and not used

### ISSUE THREAD

**Issue by tonysyu** [tonysyu/qwikstart#126]
When defining local context on an operation, it can be helpful to ensure that variables defined are actually used by the operation. For example, the follow code below will silently ignore the misspelled `op_config` variable (should be `opconfig`):
```yaml
steps:
    "Define name":
        name: define_context
        op_config:
            output_namespace: "template_variables"
        context_defs:
            name: "World"
```
We can't know whether global context is misspelled, but local context will only ever be used by the operation where it's defined and should raise an error if not used.
