### ISSUE TITLE
Allow (or prefer?) local-context to be passed to operations as "top-level" parameters in yaml

### ISSUE THREAD

**Issue by tonysyu** [tonysyu/qwikstart#29]
Currently, local context can be passed to an operation using the top-level `local_context` parameter on a given operation. For example:
```yaml
operations:
    prompt_user:
        local_context:
            prompts:
                - name: "name"
                  default_value: "World"
```
Given the ubiquity of these context variables, it seems useful to remove the extra nesting if possible; e.g.:
```yaml
operations:
    prompt_user:
        prompts:
            - name: "name"
              default_value: "World"
```
This would obviously introduce the potential for context variables to collide with operation parameters (currently, just `local_context`, `mapping`, `input_mapping`, and `output_mapping`), but we could restrict these names as context variables to avoid this issue.

In addition, we could nest configuration parameters to operations under a separate top-level parameter; e.g. `operation_config`:
```yaml
operations:
    prompt_user:
        prompts:
            - name: "name"
              default_value: "World"
        operation_config:
            input_mapping: ...
```
