### ISSUE TITLE
Error when integer default given for prompt input

### ISSUE THREAD

**Issue by tonysyu** [tonysyu/qwikstart#53]
The following `qwikstart.yml`:
```
operations:
    prompt:
        inputs:
            - name: "localhost_app_port"
              default_value: 8000
```
Will throw the following error:
```
TypeError: object of type 'int' has no len()
```
