### ISSUE TITLE
Change qwikstart.yml's dict-definitions for operations to avoid overwriting operations

### ISSUE THREAD

**Issue by tonysyu** [tonysyu/qwikstart#63]
The `qwikstart.yml` definition currently allows `operations` to be defined as a single dictionary. This causes problems when using the same operations within the same `qwikstart.yml`; e.g.:
```yaml
operations:
  append_text:
    file_path: "requirements.txt"
    text: "requests"
  append_text:
    file_path: "requirements.test"
    text: "pytest"
```
This example can currently be fixed by using lists:
```yaml
operations:
  - append_text:
      file_path: "requirements.txt"
      text: "requests"
  - append_text:
      file_path: "requirements.test"
      text: "pytest"
```
We could just stop supporting dictionaries. Alternatively, we could support change the dictionaries so that the keys are operation descriptions:
```yaml
operations:
  Add requirements:
    op: append_text
    file_path: "requirements.txt"
    text: "requests"
  Add test requirements:
    op: append_text
    file_path: "requirements.test"
    text: "pytest"
```
It would also be nice to support multiple operations per description; e.g.:
```yaml
operations:
  Add newdjangoapp urls:
    - op: find_tagged_line
      file_path: "proj/urls.py"
      tag: "# qwikstart: inject-urlpatterns"
    - insert_text:
      file_path: "proj/urls.py"
      text: "path('newdjangoapp/', include('newdjangoapp.urls')),"
```
