### ISSUE TITLE
Add support for syntax highlighting in `echo` operation

### ISSUE THREAD

**Issue by tonysyu** [tonysyu/qwikstart#64]
Currently, you can use the `colored` template filter for rendering colored text to the terminal. For example:
```yaml
operations:
    echo:
        message: |
            {{ 'Hello world!' | colored("yellow") }}
```
It would be nice to support highlighting code output to the terminal using something like [pygments](https://pygments.org/faq/). For example, this might look something like:
```yaml
operations:
    echo:
        highlight: python
        message: |
            def greetings():
                print("Hello world!")
```
