### ISSUE TITLE
Allow limiting scope of context data to a series of operations

### ISSUE THREAD

**Issue by tonysyu** [tonysyu/qwikstart#67]
By default, context data is propagated throughout a given task. This allows easy chaining of operations to create useful output. That said, it's also useful to limit the scope of context data. For example:
```yaml
operations:
    - find_tagged_line:
        file_path: "proj/urls.py"
        tag: "# qwikstart: inject-urlpatterns"
    - insert_text:
        file_path: "proj/urls.py"
        text: "path('newdjangoapp/', include('newdjangoapp.urls')),"
    - insert_text:
        file_path: "proj/templates/base.html"
        text: "{% load static %}"
        line: 0
```
The second call to `insert_text` above will re-use the `column` from the `find_tagged_line`, even though that column was meant to apply only to the first `insert_text`. It should be possible to limit the scope of context data. Underneath the hood, this might use Python's [ChainMap](https://docs.python.org/3/library/collections.html#collections.ChainMap) for implementation.

One way to define scopes might be to use the operation descriptions suggested in https://github.com/tonysyu/qwikstart/issues/63; e.g.:
```yaml
operations:
  Add newdjangoapp urls:
    - op: find_tagged_line
      file_path: "proj/urls.py"
      tag: "# qwikstart: inject-urlpatterns"
    - op: insert_text:
      file_path: "proj/urls.py"
      text: "path('newdjangoapp/', include('newdjangoapp.urls')),"
  Update base template:
    - op: insert_text:
      file_path: "proj/templates/base.html"
      text: "{% load static %}"
      line: 0
```
That said, it might be nice to have a more explicit scoping operator since it still useful to have grouped operation descriptions and share data across those grouped operations.

Another option is to allow operations to define namespaces (which would just be dictionaries nested under the top-level context dictionary): Operations would only have access to variables in this context and output would be added to this context (though maybe this should be configurable).
