### ISSUE TITLE
Add operation to parse and execute sub-tasks

### ISSUE THREAD

**Issue by tonysyu** [tonysyu/qwikstart#98]
Ideally, we would be able to define a sub-task by link to a separate file; something like:
```yaml
name: sub_task
file_path: "path/to/sub/task.yml"
context: 
    # ...
```
